-- Sample DB schema DATAFLY --
-- jdbc:hsqldb:file:<<file location --
CREATE SCHEMA DATAFLY AUTHORIZATION DBA;

-- creation of tables
-- USER---
CREATE TABLE USER (
USER_ID int  NOT NULL IDENTITY,
  USER_NAME varchar(45) NOT NULL UNIQUE,
  USER_PWD varchar(45) NOT NULL,
  CREATED_BY varchar(45) NOT NULL,
  CREATED_TIME timestamp NOT NULL ,
  UPDATED_BY varchar(45) DEFAULT NULL,
  UPDATED_TIME timestamp NULL
  );
  
 --- USER_ROLE-----

 CREATE TABLE USER_ROLE (
USER_ROLE_ID int NOT NULL IDENTITY,
  USER_ID int NOT NULL,
  USER_ROLE_TYPE_ID int NOT NULL ,
  CREATED_BY varchar(45) NOT NULL,
 CREATED_TIME timestamp NOT NULL,
  UPDATED_BY varchar(45) NULL,
  UPDATED_TIME timestamp NULL 
  ) ;

-- USER_ROLE_TYPE--

CREATE TABLE USER_ROLE_TYPE (
USER_ROLE_TYPE_ID int NOT NULL IDENTITY,
 USER_ROLE_TYP_NAME varchar(45) NOT NULL UNIQUE,
USER_ROLE_TYP_DESC varchar(45),
  CREATED_BY varchar(45) NOT NULL,
CREATED_TIME timestamp NOT NULL,
  UPDATED_BY varchar(45) NULL,
  UPDATED_TIME timestamp NULL,
 ) ;
 
 
-- USER_CONNECTION_DETAILS --

CREATE TABLE USER_CONNECTION_DETAILS (
CONNECTION_ID int NOT NULL IDENTITY,
USER_ID int NOT NULL,
CONNECTION_NAME varchar(60) NOT NULL UNIQUE,
CONNECTION_URL varchar(100) NOT NULL,
CONNECTION_SCHEMA varchar(60) NOT NULL,
CONNECTION_USER varchar(45) NOT NULL,
CONNECTION_PWD varchar(60) NOT NULL,
  CREATED_BY varchar(60) NOT NULL,
CREATED_TIME timestamp NOT NULL,
  UPDATED_BY varchar(45) NULL,
  UPDATED_TIME timestamp NULL
 ) ;


  
-- CONSTRAINTS
ALTER TABLE USER_ROLE ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (USER_ROLE_TYPE_ID) REFERENCES USER_ROLE_TYPE(USER_ROLE_TYPE_ID);
ALTER TABLE USER_CONNECTION_DETAILS ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

