package org.vivektest.hibernate.model;

// Generated Jul 4, 2015 1:23:09 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "notification", uniqueConstraints = @UniqueConstraint(columnNames = "NOTIFICATION_ID"))
public class Notification implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer notificationId;
	private String notificationName;
	private String subscriptionName;
	private String createdBy;
	private Date createdTime;
	private String updatedBy;
	private Date updatedTime;

	public Notification() {
	}

	public Notification(String subscriptionName, String notificationName, String createdBy,
			Date createdTime) {
		this.subscriptionName = subscriptionName;
		this.notificationName = notificationName;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
	}

	public Notification(String subscriptionName, String notificationName, String createdBy,
			Date createdTime, String updatedBy, Date updatedTime) {
		this.subscriptionName = subscriptionName;
		this.notificationName = notificationName;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NOTIFICATION_ID", unique = true, nullable = false)
	public Integer getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Integer notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "NOTIFICATION_NAME", nullable = false, length = 45)
	public String getNotificationName() {
		return this.notificationName;
	}

	public void setNotificationName(String notificationName) {
		this.notificationName = notificationName;
	}

	@Column(name = "SUBSCRIPTION_NAME", nullable = false, length = 45)
	public String getSubscriptionName() {
		return this.subscriptionName;
	}

	public void setSubscriptionName(String subscriptionName) {
		this.subscriptionName = subscriptionName;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "UPDATED_BY", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TIME", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
